ARG BASE_IMAGE=python:3.12-slim

FROM debian:12-slim AS base-model-downloader
RUN apt update && apt install aria2 -y

# -------------------------------------------------------------------SD1.5 CONTROLNETS----------------------------------------------------------------
FROM base-model-downloader AS sd15-controlnet-models
ARG SAVE_DIR="/models/controlnet/sd1.5"
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11p_sd15_openpose.pth" -d ${SAVE_DIR} -o "control_v11p_sd15_openpose.pth"
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11f1p_sd15_depth.pth" -d ${SAVE_DIR} -o "control_v11f1p_sd15_depth.pth"
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11p_sd15_lineart.pth" -d ${SAVE_DIR} -o "control_v11p_sd15_lineart.pth"
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11p_sd15_softedge.pth" -d ${SAVE_DIR} -o "control_v11p_sd15_softedge.pth"
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11f1e_sd15_tile.pth" -d ${SAVE_DIR} -o "control_v11f1e_sd15_tile.pth"
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11p_sd15_inpaint.pth" -d ${SAVE_DIR} -o "control_v11p_sd15_inpaint.pth"
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11e_sd15_ip2p.pth" -d ${SAVE_DIR} -o "control_v11e_sd15_ip2p.pth"
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M "https://huggingface.co/monster-labs/control_v1p_sd15_qrcode_monster/resolve/main/control_v1p_sd15_qrcode_monster.ckpt" -d ${SAVE_DIR} -o "control_v1p_sd15_qrcode_monster.pth"
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M "https://huggingface.co/guoyww/animatediff/resolve/main/v3_sd15_sparsectrl_rgb.ckpt" -d ${SAVE_DIR} -o "v3_sd15_sparsectrl_rgb.pth"

# -------------------------------------------------------------------ANIMATEDIFF----------------------------------------------------------------------
FROM base-model-downloader AS animatediff-models
ARG SAVE_DIR="/models/animatediff_models"
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M "https://huggingface.co/wangfuyun/AnimateLCM/resolve/main/AnimateLCM_sd15_t2v.ckpt" -d ${SAVE_DIR} -o "AnimateLCM_sd15_t2v.ckpt"
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M "https://huggingface.co/guoyww/animatediff/resolve/main/v3_sd15_mm.ckpt" -d ${SAVE_DIR} -o "v3_sd15_mm.ckpt"

# -------------------------------------------------------------------SD1.5 Models---------------------------------------------------------------------
FROM base-model-downloader AS sd15-models
ARG SAVE_DIR="/models/checkpoints/sd1.5"
ARG CIVITAI_TOKEN
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M "https://huggingface.co/jzli/DreamShaper-8/resolve/main/dreamshaper_8.safetensors" -d ${SAVE_DIR} -o "dreamshaper_8.safetensors"
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M "https://huggingface.co/ckpt/flat-2d-animerge/resolve/main/flat2DAnimerge_v10.safetensors" -d ${SAVE_DIR} -o "flat2d_animerge.safetensors"
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M "https://huggingface.co/digiplay/Photon_v1/resolve/main/photon_v1.safetensors" -d ${SAVE_DIR} -o "photon_v1.safetensors"
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://civitai.com/api/download/models/344398?token=${CIVITAI_TOKEN} -d ${SAVE_DIR} -o "photon_lcm.safetensors"
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://civitai.com/api/download/models/401653?token=${CIVITAI_TOKEN} -d ${SAVE_DIR} -o "delusions_lcm.safetensors"

# -------------------------------------------------------------------SDXL Models---------------------------------------------------------------------
FROM base-model-downloader AS sdxl-models
ARG SAVE_DIR="/models/checkpoints/sdxl"
ARG CIVITAI_TOKEN
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://civitai.com/api/download/models/354657?token=${CIVITAI_TOKEN} -d ${SAVE_DIR} -o "dreamshaper_xl_lightning.safetensors"
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://civitai.com/api/download/models/361593?token=${CIVITAI_TOKEN} -d ${SAVE_DIR} -o "RealVisXL_V4.0_Lightning_BakedVAE.safetensors"
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://civitai.com/api/download/models/357609?token=${CIVITAI_TOKEN} -d ${SAVE_DIR} -o "Juggernaut_RunDiffusionPhoto2_Lightning_4Steps.safetensors"

# -------------------------------------------------------------------Flux Models---------------------------------------------------------------------
FROM base-model-downloader AS flux-models
ARG SAVE_DIR="/models/checkpoints/flux"
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M "https://huggingface.co/Comfy-Org/flux1-schnell/resolve/main/flux1-schnell-fp8.safetensors" -d ${SAVE_DIR} -o "flux1-schnell-fp8.safetensors"

# ---------------------------------------------------------IP Adapter models---------------------------------------------------------------------
FROM base-model-downloader AS ipadapter-models

ARG SAVE_DIR="/models/clip_vision"
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M "https://huggingface.co/h94/IP-Adapter/resolve/main/models/image_encoder/model.safetensors" -d ${SAVE_DIR} -o "CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors"
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M "https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/image_encoder/model.safetensors" -d ${SAVE_DIR} -o "CLIP-ViT-bigG-14-laion2B-39B-b160k.safetensors"

ARG SAVE_DIR="/models/ipadapter"
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M "https://huggingface.co/h94/IP-Adapter/resolve/main/models/ip-adapter-plus_sd15.safetensors" -d ${SAVE_DIR} -o "ip-adapter-plus_sd15.safetensors"
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M "https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/ip-adapter-plus_sdxl_vit-h.safetensors" -d ${SAVE_DIR} -o "ip-adapter-plus_sdxl_vit-h.safetensors"


# -------------------------------------------------------------------Other Models---------------------------------------------------------------------
FROM base-model-downloader AS other-models
# vae
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M "https://huggingface.co/stabilityai/sd-vae-ft-mse-original/resolve/main/vae-ft-mse-840000-ema-pruned.ckpt" -d "/models/vae" -o "vae-ft-mse-840000-ema-pruned.ckpt"
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M "https://huggingface.co/hakurei/waifu-diffusion-v1-4/resolve/main/vae/kl-f8-anime2.ckpt" -d "/models/vae" -o "kl-f8-anime2.ckpt"
# lora
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M "https://huggingface.co/latent-consistency/lcm-lora-sdv1-5/resolve/main/pytorch_lora_weights.safetensors" -d "/models/loras" -o "lcm_sd15.safetensors"
# facerestore
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M "https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/codeformer.pth" -d "/models/facerestore_models" -o "codeformer.pth"
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M "https://github.com/TencentARC/GFPGAN/releases/download/v1.3.0/GFPGANv1.4.pth" -d "/models/facerestore_models" -o "GFPGANv1.4.pth"
# instantid
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M "https://huggingface.co/InstantX/InstantID/resolve/main/ip-adapter.bin" -d "/models/instantid" -o "ip-adapter.bin"
RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M "https://huggingface.co/InstantX/InstantID/resolve/main/ControlNetModel/diffusion_pytorch_model.safetensors" -d "/models/controlnet" -o "instantid.safetensors"
# insightface
RUN apt install unzip && \
    aria2c --console-log-level=error -c -x 16 -s 16 -k 1M "https://huggingface.co/MonsterMMORPG/tools/resolve/main/antelopev2.zip" -d "/models/insightface/models" -o "antelopev2.zip" && \
    cd /models/insightface/models && unzip antelopev2.zip && \
    rm antelopev2.zip 



# -------------------------------------------------------------------Final---------------------------------------------------------------------
ARG BASE_IMAGE
FROM $BASE_IMAGE AS final

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1 \
    NVIDIA_VISIBLE_DEVICES=all \
    NVIDIA_DRIVER_CAPABILITIES=all

ARG WORKDIR
WORKDIR ${WORKDIR}

RUN apt update -y && apt install git wget ffmpeg -y

ARG COMFYUI_SHA
RUN git clone https://github.com/comfyanonymous/ComfyUI

WORKDIR ${WORKDIR}/ComfyUI

RUN git checkout ${COMFYUI_SHA}

ARG PYTORCH_VERSION
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install torch==${PYTORCH_VERSION} jupyterlab && \
    pip install -r requirements.txt

RUN git -C ./custom_nodes clone --depth 1 https://github.com/ltdrdata/ComfyUI-Manager.git && \
    git -C ./custom_nodes clone --depth 1 https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite.git && \
    git -C ./custom_nodes clone --depth 1 https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet.git && \
    git -C ./custom_nodes clone --depth 1 https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved && \
    git -C ./custom_nodes clone --depth 1 https://github.com/Fannovel16/comfyui_controlnet_aux.git && \
    git -C ./custom_nodes clone --depth 1 https://github.com/Fannovel16/ComfyUI-Frame-Interpolation.git && \
    git -C ./custom_nodes clone --depth 1 https://github.com/jags111/efficiency-nodes-comfyui.git && \
    git -C ./custom_nodes clone --depth 1 https://github.com/kijai/ComfyUI-KJNodes.git && \
    git -C ./custom_nodes clone --depth 1 https://github.com/cubiq/ComfyUI_IPAdapter_plus.git && \
    git -C ./custom_nodes clone --depth 1 https://github.com/cubiq/ComfyUI_essentials.git && \
    git -C ./custom_nodes clone --depth 1 https://github.com/FizzleDorf/ComfyUI_FizzNodes.git && \
    git -C ./custom_nodes clone --depth 1 https://github.com/cubiq/ComfyUI_InstantID && \
    git -C ./custom_nodes clone --depth 1 https://github.com/SuperBeastsAI/ComfyUI-SuperBeasts && \
    git -C ./custom_nodes clone --depth 1 https://github.com/mav-rik/facerestore_cf.git && \
    git -C ./custom_nodes clone --depth 1 https://github.com/theUpsider/ComfyUI-Logic.git && \
    git -C ./custom_nodes clone --depth 1 https://github.com/banodoco/Steerable-Motion.git && \
    git -C ./custom_nodes clone --depth 1 https://github.com/yuvraj108c/ComfyUI-Pronodes

COPY scripts/* .

# insightface
RUN apt install gcc g++ -y
RUN pip install wheel && \
    pip install insightface

RUN chmod +x ./install-nodes-dependencies.sh
RUN --mount=type=cache,target=/root/.cache/pip \
    ./install-nodes-dependencies.sh

COPY --from=sd15-controlnet-models /models/* ./models/controlnet
COPY --from=animatediff-models /models/* ./models/animatediff_models
COPY --from=ipadapter-models /models/ipadapter ./models/ipadapter
COPY --from=ipadapter-models /models/clip_vision ./models/clip_vision

COPY --from=other-models /models/loras ./models/loras
COPY --from=other-models /models/vae ./models/vae
COPY --from=other-models /models/facerestore_models ./models/facerestore_models
COPY --from=other-models /models/instantid ./models/instantid
COPY --from=other-models /models/insightface ./models/insightface
COPY --from=other-models /models/controlnet ./models/controlnet
COPY --from=flux-models /models/* ./models/checkpoints
COPY --from=sdxl-models /models/* ./models/checkpoints
COPY --from=sd15-models /models/* ./models/checkpoints

RUN chmod +x ./setup-ssh.sh
RUN chmod +x ./start.sh

# RUN ./setup-ssh.sh

CMD ["/workspace/ComfyUI/start.sh"]
